#! /bin/sh

# Start sxhkd
pgrep -x sxhkd > /dev/null || sxhkd &

# Start dunst
$HOME/.config/dunst/start.sh &

# Start polybar
$HOME/.config/polybar/launch.sh &

# Assign displays
bspc monitor DisplayPort-2 -d		I III V
bspc monitor HDMI-A-0 -d		    II IV VI

# Source wal colors
. "${HOME}/.cache/wal/colors.sh"

# WM configuration
bspc config border_width         1
bspc config window_gap          25

bspc config split_ratio          0.52
bspc config borderless_monocle   true

bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1"

# Window rules
bspc rule -a discord desktop=^5
bspc rule -a Zathura state=tiled
bspc rule -a Picture-in-Picture state=floating
