#! /bin/sh

### Background Processes ###

# Start picom
pgrep -x picom > /dev/null || picom -b

# Start sxhkd
pgrep -x sxhkd > /dev/null || sxhkd &

# Start fcitx5
fcitx5 -rd &

# Start dunst
$HOME/.config/dunst/start.sh &

# Start polybar
$HOME/.config/polybar/launch.sh &

### BSPWM Config ###

# Assign displays
## Personally, I organize windows according to pairs of displays in the order project1, project2, entertainment, school.
bspc monitor DisplayPort-2 -d		I II III IV
bspc monitor HDMI-A-0 -d		    V VI VII IX

# WM configuration
bspc config border_width         1
bspc config window_gap          15

# Source Luthien Colors
. ~/.local/share/luthien/outputs/plugins/templates/bspwm.sh

# Window rules
bspc rule -a discord desktop=^7
bspc rule -a Zathura state=tiled
bspc rule -a Picture-in-Picture state=floating
