wallpaper = "/home/max/pictures/wallpaper/gruvbox-light-archlinux2.png"

[colors]
background = "fbf1c7"
foreground = "3c3836"

accents = [
  "cc241d",
  "98971a",
  "458588",
  "b16286",
  "689d6a",
  "d79921",
]

  [colors.palette]
  black = "3c3836"
  red = "cc241d"
  green = "98971a"
  yellow = "d79921"
  blue = "458588"
  purple = "b16286"
  cyan = "689d6a" # Not really cyan, but what can you do.
  white = "fbf1c7"
